//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string ProductsName { get; set; }
        public string ProductsID { get; set; }
        public int CategroiesId { get; set; }
    
        public virtual Categroies Categroies { get; set; }
    }
}
